import React , {Component} from 'react';
import {ImageBackground,Text,StyleSheet,View,ScrollView,Modal} from 'react-native';

export default class ListDetail extends Component{

    state={

        H:{
            name:'Hydrogen',
            number:'1',
            group:'1',
            period:'1',
            mass:'1.0079',
            radius:'37.3pm',
            oxidation:'-1/+1',
            electronegativity:'2.2',
            meltingPoint:'-259.34 C',
            boilingPoint:'-252.87 C',
            about:'Hydrogen was discovered by Sir Henry Cavendish(England) in 1766.The origin of the name comes from the Greek words hydro and genes meaning water and generate.It is colourless,odourless gas,burns and forms explosive mixtures in air.Reacts violently with oxidants.Hydrogen is the most abundant element in the universe.',
        },

        HE:{
            name:'Helium',
            number:'2',
            group:'18',
            period:'1',
            mass:'4.0026',
            radius:'128pm',
            oxidation:'0',
            electronegativity:'',
            meltingPoint:'-272.2 C',
            boilingPoint:'-268.93 C',
            about:'Helium was discovered by Pierre Jules Cesar Janssen(France) and Sir William Ramsay(Scotland) in 1868.The origin of the name comes from Greek word helios meaning sun.It is light,odourless,colourless inert gas.Second most abundant element in the universe.',
        },

        LI:{
            name:'Lithium',
            number:'3',
            group:'1',
            period:'2',
            mass:'6.941',
            radius:'152pm',
            oxidation:'+1',
            electronegativity:'0.98',
            meltingPoint:'180.5 C',
            boilingPoint:'1342 C',
            about:'Lithium was discovered by Johan August Arfvedson(Sweden) in 1817.The origin of the name comes from the Greek word lithos meaning stone,apparently because it was discovered from a mineral source whereas the other two elements ,sodium and potassium,were discovered from plant sources.It is soft silvery-white metal.Lightest of metals.React slowly with water and oxygen.Flammable.Can ignite in air.Reacts with water to give off a flammable gas.',
        },

        BE:{
            name:'Beryllium',
            number:'4',
            group:'2',
            period:'2',
            mass:'9.0121',
            radius:'111.3pm',
            oxidation:'+2',
            electronegativity:'1.57',
            meltingPoint:'1287 C',
            boilingPoint:'2471 C',
            about:'Beryllium was discovered by Friedrich Wohler(Germany) and independently by A.B.Bussy(France) in 1828. The origin of the name comes from the Greek word beryllos meaning mineral beryl.It is steel-grey metal.It resists attack by concentrated nitric acid , has excellent thermal conductivity and is nonmagnetic.At ordinary temperatures,it resists oxidation in air.Beryllium and its salts are toxic and should be handled with the greatest of care.',
        },

        B:{
            name:'Boron',
            number:'5',
            group:'13',
            period:'2',
            mass:'10.811',
            radius:'79.5pm',
            oxidation:'+3',
            electronegativity:'2.04',
            meltingPoint:'2075 C',
            boilingPoint:'4000 C',
            about:'Boron compounds have been known for thousands of years,but the element was not discovered until 1808 by Sir Humphry Davy(England) and independently by Joseph-Louis Gay-Lussac(France) and L.J.Thenard(France).The origin of the name comes from Arabic word buraqand the Persian word burah meaning boraks(Na2B4O7 * 10H2O).It is hard,brittle,lustrous black semimetal.Unreactive with oxygen,water,alkalis or acids.Combines with most metals to form borides.',
        },


        C:{
            name:'Carbon',
            number:'6',
            group:'14',
            period:'2',
            mass:'12.0107',
            radius:'77.2pm',
            oxidation:'-4/+2/+4',
            electronegativity:'2.55',
            meltingPoint:'3550 C',
            boilingPoint:'4827 C',
            about:'Carbon has been known since ancient times.The origin of the name comes from the Latin word carbo meaning charcoal.Graphite form of carbon is a black,odourless,slippery solid.Graphite sublimes at 3825 C.Diamond form is a clear of colored,an extremely hard solid.C60 is Buckminsterfullerine.Carbon black burns readily with oxidants.',
        },

        N:{
            name:'Nitrogen',
            number:'7',
            group:'15',
            period:'2',
            mass:'14.0067',
            radius:'54.9pm',
            oxidation:'-3/-2/-1/+1/+2/+3/+4/+5',
            electronegativity:'3.04',
            meltingPoint:'-210 C',
            boilingPoint:'-195.8 C',
            about:'Nitrogen was discovered by Daniel Rutherford(Scotland) in 1772.It is colourless,odourless,generally inert gas.Minimally reactive at room temperature.A component of many organic and inorganic compounds.Makes up about 78% of earth atmosphere.',
        },

        O:{
            name:'Oxygen',
            number:'8',
            group:'16',
            period:'2',
            mass:'15.9994',
            radius:'60.4pm',
            oxidation:'-2',
            electronegativity:'3.44',
            meltingPoint:'-218.79 C',
            boilingPoint:'-182.95 C',
            about:'Oxygen was discovered by Joseph Priestley(England) in 1774.It is colourless,odourless gas, pale blue liquid.Extremely reactive.Forms oxides with nearly all other elements except noble gases.IT is the most abundant element in the earth crust and makes up almost 21% of the atmosphere.',
        },

         F:{
            name:'Fluorine',
            number:'9',
            group:'17',
            period:'2',
            mass:'18.998',
            radius:'70.9pm',
            oxidation:'-1',
            electronegativity:'3.98',
            meltingPoint:'-219.62 C',
            boilingPoint:'-188.12 C',
            about:'Fluorine was discovered by Henri Moissan(France) in 1886.It is pale yellow to greenish gas,with an irritating pungent odour.Extremely reactive,flammable gas.React violently with many materials.Toxic by inhalation or ingestion.Does not occur uncombined in nature.',
        },

        NE:{
            name:'Neon',
            number:'10',
            group:'18',
            period:'2',
            mass:'20.179',
            radius:'154pm',
            oxidation:'0',
            electronegativity:'',
            meltingPoint:'-248.59 C',
            boilingPoint:'-246.08 C',
            about:'Neon was discovered by Sir William Ramsay and Morris W. Travers(England) in 1898.It is colourless,odourless inert gas.Non-reactive even with fluorine.Fourth most abundant element in the universe.',
        },

        NA:{
            name:'Sodium',
            number:'11',
            group:'1',
            period:'3',
            mass:'22.9897',
            radius:'185.8pm',
            oxidation:'+1',
            electronegativity:'0.93',
            meltingPoint:'97.72 C',
            boilingPoint:'883 C',
            about:'Sodium was discovered by Sir Humphry Davy(England) in 1807.It is soft silvery-white metal.Fresh surfaces oxidize rapidly.Reacts vigorously,even violently with water.Reacts with water to give off flammable gas.Burns in air with a briliant white flame.',
        },

        MG:{
            name:'Magnesium',
            number:'12',
            group:'2',
            period:'3',
            mass:'24.305',
            radius:'159.9pm',
            oxidation:'+2',
            electronegativity:'1.31',
            meltingPoint:'650 C',
            boilingPoint:'1090 C',
            about:'Magnesium was discovered by Sir Humphry Davy(England) in 1808.It is light weight,malleable,silvery-white metal.Burns in air with a brilliant white flame and reacts with water as temperature elevates.Can ignite in air.React violently with oxidants.',
        },

          AL:{
            name:'Aluminium',
            number:'13',
            group:'13',
            period:'3',
            mass:'26.9815',
            radius:'143.2pm',
            oxidation:'+3',
            electronegativity:'1.61',
            meltingPoint:'660.32 C',
            boilingPoint:'2519 C',
            about:'Aluminium was discovered by Friedrich Wohler(Germany) in 1827.It is soft,light weight,silvery-white metal.Exposed surfaces quickly form protective oxide coating.Metal reacts violently with oxidants.Third most abundant element in the earth crust.',
        },

        SI:{
            name:'Silicon',
            number:'14',
            group:'14',
            period:'3',
            mass:'28.0855',
            radius:'117.6pm',
            oxidation:'-4/+2/+4',
            electronegativity:'1.9',
            meltingPoint:'1414 C',
            boilingPoint:'3265 C',
            about:'Silicon was discovered by Jons Jacob Berzelius(Sweden) in 1824.Amorphous form of silicon is brown powder,crystalline form has grey metallic appearance.Solid form unreactive with oxygen,water and most acids.Dissolves in hot alkali.Silica dust is a moderately toxic acute irritant.',
        },

          P:{
            name:'Phosphorus',
            number:'15',
            group:'15',
            period:'3',
            mass:'30.9737',
            radius:'110.5pm',
            oxidation:'-3/+3/+5',
            electronegativity:'2.19',
            meltingPoint:'44.15 C',
            boilingPoint:'280.5 C',
            about:'Phosphorus was discovered by Hennig Brandt(Germany) in 1669.White phosphorus is white to yellow soft,waxy phosphorescent solid with acrid fumes.Toxic by inhalation,ingestion,or skin contact.Red phosphorus is powdery,non-flammable and non-toxic.',
        },

      S:{
            name:'Sulfur',
            number:'16',
            group:'16',
            period:'3',
            mass:'32.065',
            radius:'103.5pm',
            oxidation:'-2/+4/+6',
            electronegativity:'2.58',
            meltingPoint:'115.21 C',
            boilingPoint:'444.60 C',
            about:'Sulfur has been known since ancient times.It is pale yellow,odourless,brittle solid,which is insoluble in water but soluble in carbon disulfide.',
        },


      CL:{
            name:'Chlorine',
            number:'17',
            group:'17',
            period:'3',
            mass:'35.453',
            radius:'99.4pm',
            oxidation:'-1/+1/+5/+7',
            electronegativity:'3.16',
            meltingPoint:'-101.5 C',
            boilingPoint:'34.04 C',
            about:'Chlorine was discovered by Carl William Scheele(Sweden) in 1774.It is greenish-yellow,disagreeable gas with irritating odour.Gas is toxic and severe irritant by contact or inhalation.Never found in free form in nature.',
        },


      AR:{
            name:'Argon',
            number:'18',
            group:'18',
            period:'3',
            mass:'39.948',
            radius:'188pm',
            oxidation:'0',
            electronegativity:'',
            meltingPoint:'-189.34 C',
            boilingPoint:'-185.89 C',
            about:'Argon was discovered by Lord Raleigh and Sir William Ramsay(Scotland) in 1894.It is colourless and odourless noble gas.Chemically inert.It is the third most abundant element in the earth atmosphere and makes up about 1%.',
      },

      K:{
            name:'Potassium',
            number:'19',
            group:'1',
            period:'4',
            mass:'39.0983',
            radius:'227.2pm',
            oxidation:'+1',
            electronegativity:'0.82',
            meltingPoint:'63.38 C',
            boilingPoint:'759 C',
            about:'Potassium was discovered by Sir Humphry Davy(England) in 1807.It is soft,waxy,silver-white metal.Fresh surface has silvery sheen.Quickly forms dull oxide coating on exposure to air.Reacts strongly with water.Reacts with water to give off flammable gas.Reacts violently with oxidants.Occurs only in compounds.',
        },


      CA:{
            name:'Calcium',
            number:'20',
            group:'2',
            period:'4',
            mass:'40.078',
            radius:'197.4pm',
            oxidation:'+2',
            electronegativity:'1',
            meltingPoint:'842 C',
            boilingPoint:'1484 C',
            about:'Calcium was discovered by Sir Humphry Davy(England) in 1808.It is fairly hard,silvery-white metal.Exposed surfaces form oxides and nitrides.Reacts with water and oxygen.Occurs only in compounds.',
        },


      SC:{
            name:'Scadium',
            number:'21',
            group:'3',
            period:'4',
            mass:'44.9559',
            radius:'160.6pm',
            oxidation:'+3',
            electronegativity:'1.36',
            meltingPoint:'1541 C',
            boilingPoint:'2836 C',
            about:'Scandium was discovered by Lars Fredrik Nilson(Sweden) in 1879.It is fairly soft,silvery-white metal.Burns easily.Tamishes readily in air.Reaction with water releases hydrogen.Reacts with air and halogens.',
        },

         TI:{
            name:'Titanium',
            number:'22',
            group:'4',
            period:'4',
            mass:'47.867',
            radius:'144.8pm',
            oxidation:'+2/+3/+4',
            electronegativity:'1.54',
            meltingPoint:'1668 C',
            boilingPoint:'3287 C',
            about:'Titanium was discovered by William Gregor(England) in 1791.It is shiny,dark-grey metal.Powdered form burns in air.Exposed surfaces form oxide coating.It can be highly polished and is relatively immune to tarnishing.Unreactive with alkali and most acids.',
        },


         V:{
            name:'Vanadium',
            number:'23',
            group:'5',
            period:'4',
            mass:'50.9415',
            radius:'131.1pm',
            oxidation:'+2/+3/+4/+5',
            electronegativity:'1.63',
            meltingPoint:'1910 C',
            boilingPoint:'3407 C',
            about:'Vanadium was discovered by A.M.del Rio(Spain) in 1801 and rediscovered ny Nils Sefstrom(Sweden) in 1830.It is soft,ductile,silvery-white meta.Tesistant to corrosion by moisture,air and most acids and alkalis at room temperature.Exposed sufaces form oxide coating.Reacts with concentrated acids.',
        },


         CR:{
            name:'Chromium',
            number:'24',
            group:'6',
            period:'4',
            mass:'51.9961',
            radius:'124.9pm',
            oxidation:'+2/+3/+6',
            electronegativity:'1.66',
            meltingPoint:'1907 C',
            boilingPoint:'2671 C',
            about:'Chromium was discovered by Louis-Nicholas Vauquelin(France) in 1797.Ot is very hard,crystalline,steel-grey metal.The pure metal has a blue-white colour.It is corrosion-resistant at normal temperatures.Hexavalent compounds toxic by skin contact.',
        },


         MN:{
            name:'Manganese',
            number:'2',
            group:'7',
            period:'4',
            mass:'54.9380',
            radius:'136.7pm',
            oxidation:'+2/+3/+4/+7',
            electronegativity:'1.55',
            meltingPoint:'1246 C',
            boilingPoint:'2061 C',
            about:'Manganese was discovered by Johann Gahn(Sweden) in1774.It is hard,brittle,grey-white metal with a pinkish tinge.Impure forms are reactive.Rusts like iron in moist air.',
        },


         FE:{
            name:'Iron',
            number:'26',
            group:'8',
            period:'4',
            mass:'55.845',
            radius:'124.1pm',
            oxidation:'+2/+3',
            electronegativity:'1.83',
            meltingPoint:'1538 C',
            boilingPoint:'2861 C',
            about:'Iron has been known since ancient times.It is malleable,ductile,silvery-white metal.Exposed sufaces form red-brown oxides.Forms very strong alloys(steel).Ferromagnetic.Metal dust flammable.Fourth most abundant element in the earth crust.',
        },


         CO:{
            name:'Cobalt',
            number:'27',
            group:'9',
            period:'4',
            mass:'58.9332',
            radius:'125.3pm',
            oxidation:'+2/+3',
            electronegativity:'1.88',
            meltingPoint:'1495 C',
            boilingPoint:'2927 C',
            about:'Cobalt was discovered by Georg Brandt(Germany) in 1735.It is hard,ductile,lustrous bluish-grey metal.Surfaces stable in air.Reacts over time with dilute acids.It has remarkable magnetic properties.',
        },


         NI:{
            name:'Nickel',
            number:'28',
            group:'10',
            period:'4',
            mass:'58.6934',
            radius:'124.6pm',
            oxidation:'+2/+3',
            electronegativity:'1.91',
            meltingPoint:'1455 C',
            boilingPoint:'2913 C',
            about:'Nickel was discovered by Axel Fredrik Cronstedt(Sweden) in 1751.It is hard,malleable,silvery-white metal.Soluble in acids,resist alkalis.It can be polished to a lustrous finish.Resists corrosion in air under normal conditions.',
        },


         CU:{
            name:'Copper',
            number:'29',
            group:'11',
            period:'4',
            mass:'63.546',
            radius:'127.8pm',
            oxidation:'+1/+2',
            electronegativity:'1.9',
            meltingPoint:'1084.62 C',
            boilingPoint:'2562 C',
            about:'Copper has been known since ancient times.It is malleable,ductile,reddish-brown metal.Resistant to air and water.Exposed surfaces form greenish carbonate film.',
        },


         ZN:{
            name:'Zinc',
            number:'30',
            group:'12',
            period:'4',
            mass:'65.39',
            radius:'133.5pm',
            oxidation:'+2',
            electronegativity:'1.65',
            meltingPoint:'419.53 C',
            boilingPoint:'907 C',
            about:'Zinc was discovered by Andreas Marggraf(Germany) in 1746.It is bluish-silver,ductile metal.Reacts with alkalis and acids.Tarnishes in are.',
        },


         GA:{
            name:'Gallium',
            number:'31',
            group:'13',
            period:'4',
            mass:'69.723',
            radius:'122.1pm',
            oxidation:'+3',
            electronegativity:'1.81',
            meltingPoint:'29.76 C',
            boilingPoint:'2204 C',
            about:'Gallium was discovered by Lecoq de Boisbaudran(France) in 1875.It is soft,blue-white metal.Stable in air and water.Reacts violently with chlorine and bromine.',
        },


         GE:{
            name:'Germanium',
            number:'32',
            group:'14',
            period:'4',
            mass:'72.64',
            radius:'122.5pm',
            oxidation:'+2/+4',
            electronegativity:'2.01',
            meltingPoint:'938.25 C',
            boilingPoint:'2833 c',
            about:'Germanium was discovered by Clemens Winkler(Germany) in 1886.It is greyish-white semi-metal.Unaffected by alkalis and most(except nitric) acids.Stable in air and water.',
        },


         AS:{
            name:'Arsenic',
            number:'33',
            group:'15',
            period:'4',
            mass:'74.92',
            radius:'124.5pm',
            oxidation:'-3/+3/+5',
            electronegativity:'2.18',
            meltingPoint:'817 C',
            boilingPoint:'614 C',
            about:'Arsenic was discovered by Albertus Magnus(Germany) in 1250.It is steel-grey,brittle semi-metal.Resists water,acids and alkalis.Tarnishes in air,burns in oxygen.Highly toxic by inhalation or ingestion.',
        },


         SE:{
            name:'Selenium',
            number:'34',
            group:'16',
            period:'4',
            mass:'78.96',
            radius:'116pm',
            oxidation:'-2/+4/+6',
            electronegativity:'2.55',
            meltingPoint:'221 C',
            boilingPoint:'685 C',
            about:'Selenium was discovered by Jons Jakob Berzelius(Sweden) in 1817.It is soft meralloid similar to sulfur.Ranges from grey metallic to red glassy appearance.Unaffected by water.Soluble in alkalis and nitric acid.Burns in air.Toxic by inhalation or ingestion.',
        },


         BR:{
            name:'Bromine',
            number:'35',
            group:'17',
            period:'4',
            mass:'79.904',
            radius:'114.5pm',
            oxidation:'-1/+1/+5',
            electronegativity:'2.96',
            meltingPoint:'-7.2 C',
            boilingPoint:'58.78 C',
            about:'Bromine was discovered by Antoine J.Balard(France) in 1826.It is reddish-brown liquid with suffocating,irritating fumes.Gives off poisonous vapour.Causes severe burns.Oxidizer.',
        },


         KR:{
            name:'Krypton',
            number:'36',
            group:'18',
            period:'4',
            mass:'83.80',
            radius:'202pm',
            oxidation:'0',
            electronegativity:'',
            meltingPoint:'-157.36 C',
            boilingPoint:'-153.22 C',
            about:'Krypton was discovered by Sir William Ramsay and Morris W.Travers(England) in 1898.It is colourless,odourless rare noble gas.Reacts only with fluorine.',
        },


         RB:{
            name:'Rubidium',
            number:'37',
            group:'1',
            period:'5',
            mass:'85.467',
            radius:'247.5pm',
            oxidation:'+1',
            electronegativity:'0.82',
            meltingPoint:'39.31 C',
            boilingPoint:'688 C',
            about:'Rubidium was discovered by Robert Bunsen and Gusta Kirchoff(Germany) in 1861.It is soft,silvery-white,highly reactive metal.Ignites in air.Reacts violently with water or oxidants.',
        },


         SR:{
            name:'Strontium',
            number:'38',
            group:'2',
            period:'5',
            mass:'87.62',
            radius:'215.1pm',
            oxidation:'+2',
            electronegativity:'0.95',
            meltingPoint:'777 C',
            boilingPoint:'1382 C',
            about:'Strontium was discovered by Sir Humphry Davy(England) in 1808.It is soft,malleable,silvery-yellow metal.Combustible in air,will react with water.Exposed surfaces form protective oxide film.Metal ignite and burns readily.',
        },


         Y:{
            name:'Yttrium',
            number:'39',
            group:'3',
            period:'5',
            mass:'88.905',
            radius:'177.6pm',
            oxidation:'+3',
            electronegativity:'1.22',
            meltingPoint:'1522 C',
            boilingPoint:'3345 C',
            about:'Yttrium was discovered by Carl Gusta Mosander(Sweden) in 1843.It is silvery,ductile,fairly reactive metal.Exposed surfaces form oxide film.Easily combustible,reacts with oxygen in water to release hydrogen.',
        },

         ZR:{
            name:'Zirconium',
            number:'40',
            group:'4',
            period:'5',
            mass:'91.224',
            radius:'159pm',
            oxidation:'+4',
            electronegativity:'1.33',
            meltingPoint:'1855 C',
            boilingPoint:'4409 C',
            about:'Zirconium was discovered by Martin Heinrich Klaproth(Germany) in 1789.It is grey-white,lustrous,corrosion-resistant metal.Exposed surfaces form oxide protective film.',
        },


         NB:{
            name:'Niobium',
            number:'41',
            group:'5',
            period:'5',
            mass:'92.906',
            radius:'142.9pm',
            oxidation:'+3/+5',
            electronegativity:'1.6',
            meltingPoint:'2477 C',
            boilingPoint:'4744 C',
            about:'Niobium was discovered by Charles Hatchett(England) in 1801.It is shiny white,soft,ductile metal.Exposed surfaces form oxide film.',
        },


         MO:{
            name:'Molybdenum',
            number:'42',
            group:'6',
            period:'5',
            mass:'95.94',
            radius:'136.3pm',
            oxidation:'+6',
            electronegativity:'2.16',
            meltingPoint:'2623 C',
            boilingPoint:'4639 C',
            about:'Molybdenum was discovered by Carl William Scheele(Sweden) in 1778.It is silvery white,very hard metal,but is softer and more ductile than tungsten.',
        },

       TC:{
            name:'Technetium',
            number:'43',
            group:'7',
            period:'5',
            mass:'98',
            radius:'135.2pm',
            oxidation:'+4/+6/+7',
            electronegativity:'2.1',
            meltingPoint:'2157 C',
            boilingPoint:'4265 C',
            about:'Technetium was discovered by Carlo Perrier and Emilio Segre(Italy) in 1937.It is silvery-grey metal.Resists oxidation but tarnishes in moist air and burns in high oxygen environment.First synthetically produced element.Radioactive.',
        },

       RU:{
            name:'Ruthenium',
            number:'44',
            group:'8',
            period:'5',
            mass:'101.07',
            radius:'132.5pm',
            oxidation:'+3',
            electronegativity:'2.2',
            meltingPoint:'2334 C',
            boilingPoint:'4150 C',
            about:'Ruthernium was discovered by Karl Karlovich Klaus(Russua) in 1844.It is rare,extremely brittle,silver-grey metal.Unaffected by air,water or acids.Reacts with very hot(molten) alkalis.',
        },


         RH:{
            name:'Rhodium',
            number:'45',
            group:'9',
            period:'5',
            mass:'102.905',
            radius:'134.5pm',
            oxidation:'+3',
            electronegativity:'2.28',
            meltingPoint:'1964 C',
            boilingPoint:'3695 C',
            about:'Rhodium was discovered by William Hyde Wollaston(England) in 1804.It is hard,silvery-white metal.Inert in air and acids.Reacts with fused alkalis.',
        },


       PD:{
            name:'Palladium',
            number:'46',
            group:'10',
            period:'5',
            mass:'106.42',
            radius:'137.6pm',
            oxidation:'+2/+3',
            electronegativity:'2.2',
            meltingPoint:'1554.9 C',
            boilingPoint:'2963 C',
            about:'Palladium was discovered by William Hyde Wollaston(England) in 1803.It is soft,malleable,ductile,silvery-white metal.Resists corrosion,dissolves in oxidizing acids.Absords hydrogen.Metal dust is combustible.',
        },


       AG:{
            name:'Silver',
            number:'47',
            group:'11',
            period:'5',
            mass:'107.868',
            radius:'144.5pm',
            oxidation:'+1',
            electronegativity:'1.93',
            meltingPoint:'961.78 C',
            boilingPoint:'2162 C',
            about:'Silver has been known since ancient times.It is silvery-ductile and malleable metal.Stable in water and oxygen.Reacts with sulfur compounds to form black sulfides.',
        },


       CD:{
            name:'Cadmium',
            number:'48',
            group:'12',
            period:'5',
            mass:'112.411',
            radius:'148.9pm',
            oxidation:'+2',
            electronegativity:'1.69',
            meltingPoint:'321.07 C',
            boilingPoint:'767 C',
            about:'Cadmium was discovered by Friedrich Strohmeyer(Germany) in 1817.It is soft,malleable,blue-white metal.Tarnishes in air,soluble poisonous.Cadmium can cause a variety of health problems,including kidney failure and high blood pressure.',
        },


       IN:{
            name:'Indium',
            number:'49',
            group:'13',
            period:'5',
            mass:'114.818',
            radius:'162.6pm',
            oxidation:'+3',
            electronegativity:'1.78',
            meltingPoint:'156.6 C',
            boilingPoint:'2072 C',
            about:'Indium was discovered by Ferdinand Reich and Hieronymus Theodor Richter(Germany) in 1863.It is rare,very soft,silver-white metal.Stable in air and water.Dissolves in acids.Metal can ignite and burn.',
        },


       SN:{
            name:'Tin',
            number:'50',
            group:'14',
            period:'5',
            mass:'118.710',
            radius:'140.5pm',
            oxidation:'+2/+4',
            electronegativity:'1.96',
            meltingPoint:'231.93 C',
            boilingPoint:'2602 C',
            about:'Tin has been known since ancient times.It is silvery-white,soft,malleable and ductile metal.Exposed surfaces form oxide film.Resists oxygen and water.Dissolves in acids and bases.Organic tin compounds may be highly toxic.',
        },

       SB:{
            name:'Antimony',
            number:'51',
            group:'15',
            period:'5',
            mass:'121.760',
            radius:'145pm',
            oxidation:'-3/+3/+5',
            electronegativity:'2.05',
            meltingPoint:'630.63 C',
            boilingPoint:'1587 C',
            about:'Antimony has been known since ancient times.It is hard,brittle,silvery-white semimetal.Stable in dry air.Toxic by ingestion or inhalation.',
        },

       TE:{
            name:'Tellurium',
            number:'52',
            group:'16',
            period:'5',
            mass:'127.60',
            radius:'143.2pm',
            oxidation:'-2/+4/+6',
            electronegativity:'2.1',
            meltingPoint:'449.51 C',
            boilingPoint:'988 C',
            about:'Tellurium was discovered by Franz Joseph Muller von Reichstein(Romania) in 1782.It issilvery-white,brittle semi-metal.Unreactive with water or HCL,dissolves in HNO3,burns in air or oxygen.',
        },

       I:{
            name:'Iodine',
            number:'53',
            group:'17',
            period:'5',
            mass:'126.9044',
            radius:'133.1pm',
            oxidation:'-1/+1/+5/+7',
            electronegativity:'2.66',
            meltingPoint:'113.7 C',
            boilingPoint:'184.4 C',
            about:'Iodine was discovered by Bernard Courtois(France) in 1811.It is shiny,black,non-metallic solid with characteristic odour.Sublimes easily and as a gas it is violet and intensely irritating to the eyes,nose and throat.',
        },

       XE:{
            name:'Xenon',
            number:'54',
            group:'18',
            period:'5',
            mass:'131.293',
            radius:'216pm',
            oxidation:'0',
            electronegativity:'2.6',
            meltingPoint:'-111.75 C',
            boilingPoint:'-108.0 C',
            about:'Xenon was discovered by Sir William Ramsay,Morris W.Travers(England) in 1898.It is heavy,colourless,odourless,noble gas.Reacts only with fluorine.',
        },

       CS:{
            name:'Caesium',
            number:'55',
            group:'1',
            period:'6',
            mass:'132.905',
            radius:'265.5pm',
            oxidation:'+1',
            electronegativity:'0.79',
            meltingPoint:'798 C',
            boilingPoint:'3443 C',
            about:'Caesium was discovered by Robert Bunsen and Gustav Kirchhoff(Germany) in 1860.It is very soft,light grey,ductile metal.Reacts readily with oxygen.Reacts explosively with water.',
        },

       BA:{
            name:'Barium',
            number:'56',
            group:'2',
            period:'6',
            mass:'137.327',
            radius:'217.4pm',
            oxidation:'+2',
            electronegativity:'0.89',
            meltingPoint:'727 C',
            boilingPoint:'1897 C',
            about:'Barium was discovered by Sir Humphry Davy(England) in 1808.It is soft,slightly malleable,silvery-white metal.Attacked by air and water.Soluble compounds toxic by ingestion.',
        },

       LA:{
            name:'Lanthanum',
            number:'57',
            group:'3',
            period:'6',
            mass:'138.905',
            radius:'187pm',
            oxidation:'+3',
            electronegativity:'1.1',
            meltingPoint:'918 C',
            boilingPoint:'3464 C',
            about:'Lanthanum was discovered by Carl Gustaf Mosander(Sweden) in 1839.It is soft,silvery-white,malleable,ductile metal.Readily tarnishes in air.Reaction with water releases hydrogen gas.Metal ignites and burns readily.Reacts with oxidants.',
        },

       CE:{
            name:'Cerium',
            number:'58',
            group:'3',
            period:'6',
            mass:'140.116',
            radius:'182.5pm',
            oxidation:'+3/+4',
            electronegativity:'1.12',
            meltingPoint:'798 C',
            boilingPoint:'3424 C',
            about:'Cerium was discovered by Martin Heinrich Klaproth(Germany) and by Jons Jacob Berzelius(Sweden) in 1803.It is malleable,ductile,iron-grey metal.Tamishes in air,reacts easily with water.Dissolves in acids,ignites when heated.Metal ignites and burns readily.Strong reductant.',
        },

       PR:{
            name:'Praseodym',
            number:'59',
            group:'3',
            period:'6',
            mass:'140.907',
            radius:'182pm',
            oxidation:'+3',
            electronegativity:'1.13',
            meltingPoint:'931 C',
            boilingPoint:'3520 C',
            about:'Praseodymium was discovered by Carl F.Auer von Welsbach(Austria) in 1885.It is silvery white,moderately soft,malleable,ductile metal.Reacts slowly with oxygen.Reacts rapidly with water.Metal ignites and burns readily.',
        },


       ND:{
            name:'Neodymium',
            number:'60',
            group:'3',
            period:'6',
            mass:'144.24',
            radius:'181.4pm',
            oxidation:'+3',
            electronegativity:'1.14',
            meltingPoint:'1021 C',
            boilingPoint:'3074 C',
            about:'Neodymium was discovered by Carl F.Auer von Welbach(Austria) in 1885.It is silvery-white,rare-earth metal that oxidizes easily in air.Reacts slowly in cold water,more rapidly as heated.Metal ignites and burns readily.',
        },

       PM:{
            name:'Promethium',
            number:'61',
            group:'3',
            period:'6',
            mass:'145',
            radius:'183.4pm',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'1042 C',
            boilingPoint:'3000 C',
            about:'Promethium was discovered by J.A Marinsky,Lawrence Glendenin and Charles D.Coryell(USA) in 1945.It is rare earth metal of synthetic origin on the earth,naturally made in stars.Poison.Radiotoxic.Radioactive.',
        },

       SM:{
            name:'Samarium',
            number:'62',
            group:'3',
            period:'6',
            mass:'150.36',
            radius:'180.4pm',
            oxidation:'+2/+3',
            electronegativity:'1.17',
            meltingPoint:'1074 C',
            boilingPoint:'1794 C',
            about:'Samarium was discovered by Paul Emile Lecoq de Boisbaudran(France) in 1879.It is silvery rare earth metal.Stable in dry air.Oxide coating forms on surfaces exposed to moist air.Metal ignites and burns readily.Reacts with water.',
        },

       EU:{
            name:'Europium',
            number:'63',
            group:'3',
            period:'6',
            mass:'151.964',
            radius:'199.5pm',
            oxidation:'+2/+3',
            electronegativity:'',
            meltingPoint:'822 C',
            boilingPoint:'1529 C',
            about:'Europium was discovered by Eugene Damarcay(France) in 1896.It is soft,silvery-white metal.Extremely reactive with oxygen and water.',
        },

       GD:{
            name:'Gadolinium',
            number:'64',
            group:'3',
            period:'6',
            mass:'157.25',
            radius:'178.7pm',
            oxidation:'+3',
            electronegativity:'1.2',
            meltingPoint:'1313 C',
            boilingPoint:'3273 C',
            about:'Gadolinium was discovered by Jean de Marignac(France) in 1880.It is soft,ductile,silvery-white metal.Reacts slowly with water and oxygen.Dissolves in acids.Metal ignites and burns readily.',
        },

       TB:{
            name:'Terbium',
            number:'65',
            group:'3',
            period:'6',
            mass:'158.925',
            radius:'176.3pm',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'1356 C',
            boilingPoint:'3230 C',
            about:'Terbium was discovered by Carl Gustaf Mosander(Sweden) in 1843.It is soft,ductile,silvery-grey,rare earth metal.Oxidizes slowly in air.Reacts with cold water.',
        },

       DY:{
            name:'Dysprosium',
            number:'66',
            group:'3',
            period:'6',
            mass:'162.50',
            radius:'175.2pm',
            oxidation:'+3',
            electronegativity:'1.22',
            meltingPoint:'1412 C',
            boilingPoint:'2567 C',
            about:'Dysprosium was discovered by Paul Emile Lecoq de Boisbaudran(France) in 1886.It is soft,lustrous,silvery metal.Reacts with oxygen.Reacts rapidly with water,dissolves in acids.Metal ignites and burns readily.Reductant.',
        },

       HO:{
            name:'Holmium',
            number:'67',
            group:'3',
            period:'6',
            mass:'164.930',
            radius:'174.3pm',
            oxidation:'+3',
            electronegativity:'1.23',
            meltingPoint:'1474 C',
            boilingPoint:'2700 C',
            about:'Holmium was discovered by Per Theodore Cleve(Sweden) in 1879.It is fairly soft malleable,lustrous,silvery metal.Reacts slowly with oxygen and water.Dissolves in acids.Can react violently with air or halogens.',
        },

       ER:{
            name:'Erbium',
            number:'68',
            group:'3',
            period:'6',
            mass:'167.259',
            radius:'173.4pm',
            oxidation:'+3',
            electronegativity:'1.24',
            meltingPoint:'1529 C',
            boilingPoint:'2868 C',
            about:'Erbium was discovered by Carl Gusta Mosander(Sweden) in 1843.It is soft,malleable,silvery metal.Reacts slowly with water.Dissolves in acids.Metal ignites and burns readily.',
        },

       TM:{
            name:'Thulium',
            number:'69',
            group:'3',
            period:'6',
            mass:'168.934',
            radius:'172.4pm',
            oxidation:'+3',
            electronegativity:'1.25',
            meltingPoint:'1545 C',
            boilingPoint:'1950 C',
            about:'Thulium was discovered by Per Theodore Cleve(Sweden) in 1879.It is soft,malleable,ductile,silvery metal.Tarnishes in air.Reacts with water.Flammable dust.',
        },

       YB:{
            name:'Ytterbium',
            number:'70',
            group:'3',
            period:'6',
            mass:'173.04',
            radius:'194pm',
            oxidation:'+2/+3',
            electronegativity:'',
            meltingPoint:'819 C',
            boilingPoint:'1196 C',
            about:'Ytterbium was discovered by Jeans de Marignac(France) in 1878.It is silvery,lustrous,malleable and ductile metal.Oxidizes slowly in air.Reacts with water.Flammable dust.',
        },


       LU:{
            name:'Lutetium',
            number:'71',
            group:'3',
            period:'6',
            mass:'174.967',
            radius:'171.8pm',
            oxidation:'+3',
            electronegativity:'1',
            meltingPoint:'1663 C',
            boilingPoint:'3402 C',
            about:'Lutetium was discovered by Georges Urbain(France) and independently by Carl Auer von Welsbach(Austria) in 1907.It is silvery-white and relatively stable in air,rare earth metal.',
        },


       HF:{
            name:'Hafnium',
            number:'72',
            group:'4',
            period:'6',
            mass:'178.49',
            radius:'156.4pm',
            oxidation:'+4',
            electronegativity:'1.3',
            meltingPoint:'2233 C',
            boilingPoint:'4603 C',
            about:'Hafnium was discovered by Dirk Coster(Denmark) and Georg Karl von Hevesy(Hungary) in 1923.It is silvery,ductile metal.Exposed surfaces form oxide film.Resists alkalis and acids(except HF).Toxic.Metal ignites and burns readily.',
        },


       TA:{
            name:'Tantalum',
            number:'73',
            group:'5',
            period:'6',
            mass:'180.947',
            radius:'143pm',
            oxidation:'+5',
            electronegativity:'1.5',
            meltingPoint:'3017 C',
            boilingPoint:'5458 C',
            about:'Tantalum was discovered by Anders Ekeberg(Sweden) in 1802.It is rare,grey,heavy,hard but ductile metal with a high melting point.Exposed surfaces form corrosion resistant oxide film.Attacked by HF and fused alkalis.Matal ignites in air.',
        },

       W:{
            name:'Tungsten',
            number:'74',
            group:'6',
            period:'6',
            mass:'183.84',
            radius:'137pm',
            oxidation:'+6',
            electronegativity:'1.7',
            meltingPoint:'3422 C',
            boilingPoint:'5555 C',
            about:'Tungsten was discovered by Fausto and Juan de Elhuyar(Spain) in 1783.It is hard,steel-grey to white metal.Highest melting point of all metals.Resists oxygen,acids and alkalis.',
        },

       RE:{
            name:'Rhenium',
            number:'75',
            group:'7',
            period:'6',
            mass:'186.207',
            radius:'137.1pm',
            oxidation:'+4/+6/+7',
            electronegativity:'1.9',
            meltingPoint:'3186 C',
            boilingPoint:'5596 C',
            about:'Rhenium was discovered by Walter Noddack,Ida Tacke and Otto Berg(Germany) in 1925.It is rare and costly,dense,silvery-white metal.Tarnishes in moist air.Resists corrosion and oxidation.Dissolves in nitric and sulfuric acids.Has a very high melting point.',
        },

       OS:{
            name:'Osmium',
            number:'76',
            group:'8',
            period:'6',
            mass:'190.23',
            radius:'133.8pm',
            oxidation:'+3/+4',
            electronegativity:'2.2',
            meltingPoint:'3033 C',
            boilingPoint:'5012 C',
            about:'Osmium was discovered by Smithson Tennant(England) in 1803.It is hard fine black powder or hard,lustrous,blue-white metal.Unaffected by air,water and acids.Chlorine like odour due to tetroxide compound.Osmium tetroxide highly toxic.',
        },

       IR:{
            name:'Iridium',
            number:'77',
            group:'9',
            period:'6',
            mass:'192.217',
            radius:'135.7pm',
            oxidation:'+3/+4',
            electronegativity:'2.2',
            meltingPoint:'2446 C',
            boilingPoint:'4428 C',
            about:'Iridium was discovered by Smithson Tennant(England) in 1803.It is heavy,brittle,white metal.Unreactive in air,water and acids.Attacked by fused NaOH.Metal ignites and burns readily.',
        },

       PT:{
            name:'Platinum',
            number:'78',
            group:'10',
            period:'6',
            mass:'195.078',
            radius:'137.3pm',
            oxidation:'+2/+4',
            electronegativity:'2.2',
            meltingPoint:'1768.4 C',
            boilingPoint:'3825 C',
            about:'Platinum was discovered by Antonio de Ulloa(South America) in 1735.It is rare,very heavy,soft,silvery-white metal.Resists oxygen and water.',
        },

       AU:{
            name:'Gold',
            number:'79',
            group:'11',
            period:'6',
            mass:'196.966',
            radius:'144.2pm',
            oxidation:'+1/+3',
            electronegativity:'2.4',
            meltingPoint:'1064.18 C',
            boilingPoint:'2856 C',
            about:'Gold has been known since ancient times.It is soft,malleable,bright yellow metal.Unaffected by air,water,alkalis and most acids.',
        },

       HG:{
            name:'Mercury',
            number:'80',
            group:'12',
            period:'6',
            mass:'200.59',
            radius:'150.3pm',
            oxidation:'+1/+2',
            electronegativity:'1.9',
            meltingPoint:'-38.83 C',
            boilingPoint:'356.73 C',
            about:'Mercury has been known since ancient times.It is heavy,silver-white metal,liquid at ordinary temperatures.Stable in air and water.Unreactive with alkalis and most acids.Gives off poisonous vapour.Chronic cumulative effects.',
        },

       TL:{
            name:'Thallium',
            number:'81',
            group:'13',
            period:'6',
            mass:'204.383',
            radius:'170pm',
            oxidation:'+1/+3',
            electronegativity:'1.8',
            meltingPoint:'304 C',
            boilingPoint:'1473 C',
            about:'Thallium was discovered by Sir William Crookes(England) in 1861.It is soft grey metal that looks like lead.Tarnishes in moist air.Reacts in heated moist air and in acids.Compounds highly toxic by inhalation or ingestion.Cumulative effects.',
        },

       PB:{
            name:'Lead',
            number:'82',
            group:'14',
            period:'6',
            mass:'207.2',
            radius:'175pm',
            oxidation:'+2/+4',
            electronegativity:'1.8',
            meltingPoint:'327.46 C',
            boilingPoint:'1749 C',
            about:'Lead has been known since ancient times.It is very soft,highly malleable and ductile,blue-white shiny metal.Tamishes in moist air,stable in oxygen and water.Dissolves in nitric acid.Compounds toxic by inhalation or ingestion.Danger of cumulative effects.',
        },

       BI:{
            name:'Bismuth',
            number:'83',
            group:'15',
            period:'6',
            mass:'208.980',
            radius:'154.5pm',
            oxidation:'+3/+5',
            electronegativity:'1.9',
            meltingPoint:'271.4 C',
            boilingPoint:'1564 C',
            about:'Bismuth was discovered by Claude Geoffroy(France) in 1753.It is hard,brittle,steel-grey metal with a pink tint.Stable in oxygen and water.Dissolves in concentrated nitric acid.',
        },

       PO:{
            name:'Polonium',
            number:'84',
            group:'16',
            period:'6',
            mass:'209',
            radius:'167.3pm',
            oxidation:'+2/+4',
            electronegativity:'2',
            meltingPoint:'254 C',
            boilingPoint:'962 C',
            about:'Polonium was discovered by Marie Curie(Poland) in 1898.It is silvery-grey,extremely rare,radioactive metal.Soluble in dilute acids.Highly toxic.Severe radiotoxicity.Carcinogen.',
        },

       AT:{
            name:'Astatine',
            number:'85',
            group:'17',
            period:'6',
            mass:'210',
            radius:'145pm',
            oxidation:'',
            electronegativity:'2.2',
            meltingPoint:'302 C',
            boilingPoint:'337 C',
            about:'Astatine was discovered by Emilio Gino Segre,Dale R.Corson and K.R.MacKenzie(USA) in 1940.It is unstable,radioactive member of the halogen group.',
        },

       RN:{
            name:'Radon',
            number:'86',
            group:'18',
            period:'6',
            mass:'222',
            radius:'240pm',
            oxidation:'0',
            electronegativity:'',
            meltingPoint:'-71 C',
            boilingPoint:'-61.7 C',
            about:'Radon was discovered by Friedrich Ernst Dorn(Germany) in 1900.It is colourless,odourless radioactive,heavy,noble gas.Chemically inert and non-flammable.Highly radiotoxic.Carcinogen by inhalation.',
        },

       FR:{
            name:'Francium',
            number:'87',
            group:'1',
            period:'7',
            mass:'223',
            radius:'282pm',
            oxidation:'+1',
            electronegativity:'0.7',
            meltingPoint:'27 C',
            boilingPoint:'677 C',
            about:'Francium was discovered by Marguerite Perey(France) in 1939.It is highly rare and unstable,radioactive metal.Chemical properties similar to cesium.',
        },

       RA:{
            name:'Radium',
            number:'88',
            group:'2',
            period:'7',
            mass:'226',
            radius:'236pm',
            oxidation:'+2',
            electronegativity:'0.9',
            meltingPoint:'700 C',
            boilingPoint:'1140 C',
            about:'Radium was discovered by Marie and Pierre Curie(France) in 1898.It is silvery-white radioactive metal.Reacts with oxygen and water.Highly radiotoxic.Carcinogen by inhalation,ingestion,or exposure.',
        },

       AC:{
            name:'Actinium',
            number:'89',
            group:'3',
            period:'7',
            mass:'227',
            radius:'188pm',
            oxidation:'+3',
            electronegativity:'1.1',
            meltingPoint:'1051 C',
            boilingPoint:'3198 C',
            about:'Actinium was discovered by Andre Debieme(France) in 1899.It is heavy,silvery-white,very radioactive metal.Reacts with water.Glows in the dark.',
        },

       TH:{
            name:'Thorium',
            number:'90',
            group:'3',
            period:'7',
            mass:'232.038',
            radius:'179.8pm',
            oxidation:'+4',
            electronegativity:'1.3',
            meltingPoint:'1750 C',
            boilingPoint:'4788 C',
            about:'Thorium was discovered by Jons Jakob Berzelius(Sweden) in 1828.It is heavy,grey,soft,malleable,ductile,radioactive metal.Tamishes in air,reacts with water.Reacts violently with oxidants.',
        },

       PA:{
            name:'Protactinium',
            number:'91',
            group:'3',
            period:'7',
            mass:'231.035',
            radius:'156.1pm',
            oxidation:'+4/+5',
            electronegativity:'1.5',
            meltingPoint:'1572 C',
            boilingPoint:'',
            about:'Protactinium was discovered by Otto Hahn(Germany) and LIse Meitner(Austria) in 1917.It is very rare,silvery-white,extremely radioactive metal.Resists alkalis,reacts with oxygen and acids.Attacked by steam.Highly radiotoxic.Protactinium is extremely toxic and must be handled with great care.',
        },


       U:{
            name:'Uranium',
            number:'92',
            group:'3',
            period:'7',
            mass:'238.028',
            radius:'138.5pm',
            oxidation:'+3/+4/+5/+6',
            electronegativity:'1.7',
            meltingPoint:'1135 C',
            boilingPoint:'4131 C',
            about:'Uranium was discovered by Martin Heinrich Klaproth(Germany) in 1789.It is silvery-white,dense,ductile,malleable,radioactive metal.Resists alkalis,tamishes in air,attacked by steam and acids.Radiotoxic.',
        },

       NP:{
            name:'Neptunium',
            number:'93',
            group:'3',
            period:'7',
            mass:'237',
            radius:'130pm',
            oxidation:'+3/+4/+5/+6',
            electronegativity:'1.3',
            meltingPoint:'644 C',
            boilingPoint:'3902 C',
            about:'Neptunium was discovered by Edwin M.McMillan and P.H.Abelson(USA) in 1940.It is rare,silvery radioactive metal.Resists alkalis,reacts with oxygen and acids.Attacked by steam.Radiotoxic.',
        },

       PU:{
            name:'Plutonium',
            number:'94',
            group:'3',
            period:'7',
            mass:'244',
            radius:'151.3pm',
            oxidation:'+3/+4/+5/+6',
            electronegativity:'1.3',
            meltingPoint:'640 C',
            boilingPoint:'3228 C',
            about:'Plutonium was discovered by Glenn T.Seaborg,Edwin M.McMillan,J.W.Kennedy and A.C.Wahi(USA) in 1940.It is silvery-white,extremely radioactive artifically produced metal.Reacts with oxygen and acids,resists alkalis.Attacked by steam.Highly toxic.',
        },

       AM:{
            name:'Americium',
            number:'95',
            group:'3',
            period:'7',
            mass:'243',
            radius:'173pm',
            oxidation:'+3/+4/+5/+6',
            electronegativity:'',
            meltingPoint:'1176 C',
            boilingPoint:'2011 C',
            about:'Americium was discovered by Glenn T.Seaborg,Ralph A.James,Stanley in 1944.It is silvery-white,artifically produced radioactive metal.',
        },

       CM:{
            name:'Curium',
            number:'96',
            group:'3',
            period:'7',
            mass:'247',
            radius:'174pm',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'1345 C',
            boilingPoint:'',
            about:'Curium was discovered by Glenn T.Seaborg ,Ralph and Albert Ghiorso(USA) in 1944.It is silvery,malleable,synthetic radioactive metal.So radioactive it glows in the dark.',
        },

       BK:{
            name:'Berkelium',
            number:'97',
            group:'3',
            period:'7',
            mass:'247',
            radius:'170pm',
            oxidation:'+3/+4',
            electronegativity:'',
            meltingPoint:'1050 C',
            boilingPoint:'',
            about:'Berkelium was discovered by Stanley G.Thompson,Albert Ghiorso and Glenn T.Seaborg(USA) in 1949.It is synthetic radioactive metal.',
        },

       CF:{
            name:'Californium',
            number:'98',
            group:'3',
            period:'7',
            mass:'251',
            radius:'186pm',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'900 C',
            boilingPoint:'',
            about:'Californium was discovered by Stanley G.Thimpson,Kenneth Street Jr. and Albert Ghiorso(USA) in 1950.It is synthetic radioactive metal.Powerful neutron emitter.',
        },

       ES:{
            name:'Einsteinium',
            number:'99',
            group:'3',
            period:'7',
            mass:'252',
            radius:'186pm',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'860 C',
            boilingPoint:'',
            about:'Einsteinium was discovered by Albert Ghiorso(USA) in 1952.Named in honour of Albert Einstein.It is synthetic radioactive metal.',
        },

       FM:{
            name:'Fermium',
            number:'100',
            group:'3',
            period:'7',
            mass:'257',
            radius:'',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'1527 C',
            boilingPoint:'',
            about:'Fermium was discovered by Albert Ghiorso(USA) in 1953.Named in honour of Enrico Fermi.It is synthetic radioactive metal.',
        },

       MD:{
            name:'Mendelevium',
            number:'101',
            group:'3',
            period:'7',
            mass:'258',
            radius:'',
            oxidation:'+2/+3',
            electronegativity:'',
            meltingPoint:'827 C',
            boilingPoint:'',
            about:'Mendelevium was discovered by Albert Ghiorso,Bernard G.Harvey,Gregory R.Choppin,Stanley G.Thompson and Glenn T.Seaborg(USA) in 1955.Named in honour of Demitri Mendeljejeve,the Russian chemist who devised the periodic table.It is synthetic radioactive metal.',
        },

       NO:{
            name:'Nobelium',
            number:'102',
            group:'3',
            period:'7',
            mass:'259',
            radius:'',
            oxidation:'+2/+3',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Nobelium was discovered by Nobel Institute of Physics in Stockholm and later by Albert Ghiorso,Torbjom Sikkeland in 1958.Named in honour of Alfred Nobel,Swedish chemist who discovered dynamite and founder of the Nobel Prizes.It is synthetic radioactive metal.',
        },

       LR:{
            name:'Lawrencium',
            number:'103',
            group:'3',
            period:'7',
            mass:'266',
            radius:'',
            oxidation:'+3',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Lawrencium was discovered by Albert Ghiorso,Torbjorn Sikkeland,Almon E.Larsh and Robert M.Latimer(USA) in 1961.Named in honour of Ernest O.Lawrence,inventor of the cyclotron.It is synthetic radioactive metal.',
        },

       RF:{
            name:'Rutherfordium',
            number:'104',
            group:'4',
            period:'7',
            mass:'267',
            radius:'',
            oxidation:'+4',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Rutherfordium was discovered by workers at the Nuclear Institute at Dubna(USSR) and by workers at the University of California,Berkeley(USA) in 1964.Named in honour of Lord Rutherford,the physicist and chemist from New Zealand.It is synthetic radioactive metal.',
        },

       DB:{
            name:'Dubnium',
            number:'105',
            group:'5',
            period:'7',
            mass:'268',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Dubnium was discovered by workers at the Nuclear Institute at Dubna(USSR) and by workers at the University of California,Berkeley(USA) in 1967.It is synthetic radioactive metal.',
        },

       SG:{
            name:'Seaborgium',
            number:'106',
            group:'6',
            period:'7',
            mass:'269',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Seaborgium was discovered by workers at the Nuclear Institute at Dubna(USSR) and by workers at the University of California ,Berkeley(USA) in 1974.Named in honour of Glenn T.Seaborg,American nuclear chemist and Nobel prize winner.It is synthetic radioactive metal.',
        },

       BH:{
            name:'Bohrium',
            number:'107',
            group:'7',
            period:'7',
            mass:'270',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Bohrium was discovered by Peter Armbruster,Gottfried Munzenber and their co-workers at the Heavy Ion Research Laboratory in Darmstadt,Germany in 1981.Named in honour of Niels Bohr,the Danish physicist.It is synthetic radioactive metal.',
        },

       HS:{
            name:'Hassium',
            number:'108',
            group:'8',
            period:'7',
            mass:'269',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Hassium was discovered by Peter Armbruster,Gottfried Munzenber and their co-workers at the Heavy Ion Research Laboratory in Darmstadt,Germany in 1984.It is synthetic radioactive metal.',
        },

       MT:{
            name:'Meitnerium',
            number:'109',
            group:'9',
            period:'7',
            mass:'278',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Meitnerium was discovered by Peter Armbruster,Gottfried Munzenber and their other co-workers at the Heavy Ion Research Laboratory in Darmstadt,Germany in 1982.It is synthetic radioactive metal.',
        },

       DS:{
            name:'Darmstadtium',
            number:'110',
            group:'10',
            period:'7',
            mass:'281',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Darmstadtium was discovered by S.Hofmann at the Heavy Ion Research Laboratory in Darmstadt,Germany in 1994.It is synthetic radioactive metal.',
        },

       RG:{
            name:'Roentgenium',
            number:'111',
            group:'11',
            period:'7',
            mass:'282',
            radius:'',
            oxidation:'',
            electronegativity:'',
            meltingPoint:'',
            boilingPoint:'',
            about:'Roentgenium was discovered by S.Hofmann at the Heavy Ion Research Laboratory in Darmstadt,Germany in 1994.The new element has not yet been officially named ,but it is known as unununium,according to the system designated by the IUPAC for namming new elements.It is synthetic radioactive metal.',
        },

        CN:{
             name:'Copernicium',
             number:'112',
             group:'12',
             period:'7',
             mass:'285',
             radius:'147pm',
             oxidation:'0/+1/+2/+4',
             electronegativity:'',
             meltingPoint:'',
             boilingPoint:'',
             about:'It is a synthetic chemical element.Its known isotopes are extremely radioactive,and have only been created in a lab.',
         },

         NH:{
              name:'Nihonium',
              number:'113',
              group:'13',
              period:'7',
              mass:'286',
              radius:'',
              oxidation:'',
              electronegativity:'',
              meltingPoint:'',
              boilingPoint:'',
              about:'It is a synthetic chemical element.It is extremely radioactive,its most stable known isotopes,nithonium-286,has half-life of about 10 sec.',
          },

          FI:{
               name:'Flerovium',
               number:'114',
               group:'14',
               period:'7',
               mass:'289',
               radius:'',
               oxidation:'',
               electronegativity:'',
               meltingPoint:'',
               boilingPoint:'',
               about:'Flerovium is a superheavy artificial chemical element.It is extremely radioactive synthetic element.It is named after the Flerov Lab of Nuclear Reaction.',
           },


          MC:{
                name:'Moscovium',
                number:'115',
                group:'15',
                period:'7',
                mass:'290',
                radius:'',
                oxidation:'',
                electronegativity:'',
                meltingPoint:'',
                boilingPoint:'',
                about:'It is a synthetic chemical element.It was first synthesized in 2003 by a joint team of Russian and American.',
            },

            LV:{
                 name:'Livermorium',
                 number:'116',
                 group:'16',
                 period:'7',
                 mass:'293',
                 radius:'',
                 oxidation:'',
                 electronegativity:'',
                 meltingPoint:'',
                 boilingPoint:'',
                 about:'It is a synthetic chemical element.It is an extremely radioactive element that has only been created in the lab and has not been observed in the nature.',
             },

             TS:{
                  name:'Tennessine',
                  number:'117',
                  group:'17',
                  period:'7',
                  mass:'294',
                  radius:'',
                  oxidation:'',
                  electronegativity:'',
                  meltingPoint:'',
                  boilingPoint:'',
                  about:'It is synthetic chemical element.It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.',
              },


              OG:{
                   name:'Oganesson',
                   number:'118',
                   group:'18',
                   period:'7',
                   mass:'294',
                   radius:'',
                   oxidation:'',
                   electronegativity:'',
                   meltingPoint:'',
                   boilingPoint:'',
                   about:'It is a synthetic chemical element.It was first synthesized in 2002 at joint Institute for Nuclear Reasearch in Dubna,Russia.',
               },
    }



    render(){
        let element_name=this.props.element_name;
        element_name=element_name.toUpperCase();
        if(this.state[element_name])
            {
        return(


            <Modal
            visible={this.props.visibility}
            onRequestClose={this.props.closeModal}>
                <View style={{flex:1}}>
                       <ImageBackground style={{resizeMode:'cover',position:'absolute',height:'100%',width:'100%'}} source={require('../images/detail.jpeg')} blurRadius={1}>

                      <ScrollView style={{height:'100%',width:'100%'}}>

                <View style={styles.elementName}><Text style={styles.header}>{this.state[element_name].name}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>ATOMIC NUMBER           {this.state[element_name].number}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>GROUP                {this.state[element_name].group}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>PERIOD                {this.state[element_name].period}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>MASS                  {this.state[element_name].mass}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>RADIUS                {this.state[element_name].radius}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>OXIDATION              {this.state[element_name].oxidation}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>ELECTRONEGATIVITY      {this.state[element_name].electronegativity}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>MELTING POINT          {this.state[element_name].meltingPoint}</Text></View>

                <View style={styles.properties}><Text style={styles.textStyle}>BOILING POINT          {this.state[element_name].boilingPoint}</Text></View>


            <View style={styles.about}><Text style={styles.textStyle}>{this.state[element_name].about}</Text></View>

            <View style={{height:30,width:'100%'}}></View>
            </ScrollView>

        </ImageBackground>
            </View>
            </Modal>


        );
            }
        else
            {

             return(null);

            }
    }
}

const styles=StyleSheet.create({

    elementName:{
        width:'100%',
        height:'8%',
        justifyContent:'center',
        alignItems:'center',
        margin:5,
    },

    properties:{
        flex:0.01,
        justifyContent:'center',
        alignItems:'flex-start',
        marginLeft:30,
        padding:18,
    },

    textStyle:{
        fontSize:18,
        color:'white',
        textShadowOffset:{width:1,height:1},
        textShadowColor:'blue',
        textShadowRadius:5,
    },

    header:{
        fontSize:25,
        color:'red',
        textShadowOffset:{width:1,height:1},
        textShadowColor:'yellow',
        textShadowRadius:3,
    },

    about:{
       padding:10,
        marginTop:10,

    },

    about_text:{
        fontSize:20,
        color:'red',
    },

})
